#!/bin/bash

# Script de migración a Lucia Auth para ChefChek
# Este script documenta la estrategia de migración sin downtime

set -e

echo "=== Script de Documentación de Migración a Lucia Auth ==="
echo ""

echo "## Estado Actual del Sistema"
echo "- Auth: Session-based con Lucia ya implementado"
echo "- Guards: AuthGuard, TenantGuard, RolesGuard ya existen"
echo "- Sesiones: DB-based vía Prisma + Lucia"
echo "- Roles: ADMIN, USER, VIEWER ya implementados"
echo "- Permisos: Nuevo sistema granular implementado"
echo ""

echo "## Componentes Implementados"
echo "✅ LuciaAuthService - Configuración de Lucia con PrismaAdapter"
echo "✅ SessionService - Gestión de sesiones DB con refresh"
echo "✅ AuthGuard - Validación de sesiones via Authorization header"
echo "✅ PermissionsService - Sistema RBAC granular"
echo "✅ PermissionGuard - Guard para permisos específicos"
echo "✅ AuthService - Login, logout, refresh, validate completos"
echo ""

echo "## Archivos Implementados"
echo "- backend/src/modules/auth/lucia-auth.service.ts"
echo "- backend/src/modules/auth/session.service.ts"
echo "- backend/src/modules/auth/auth.service.ts"
echo "- backend/src/modules/auth/permissions.service.ts (NUEVO)"
echo "- backend/src/guards/auth.guard.ts"
echo "- backend/src/guards/permission.guard.ts (NUEVO)"
echo "- backend/src/guards/tenant.guard.ts"
echo "- backend/src/guards/roles.guard.ts"
echo "- backend/src/guards/public-guard.ts"
echo ""

echo "## Estrategia de Migración Sin Downtime"
echo ""
echo "1. **Fase Pre-Migración**"
echo "   - Backup de DB actual (sesiones, usuarios, roles)"
echo "   - Verificar dependencias: lucia, @lucia-auth, @lucia-auth/adapter-prisma"
echo "   - Crear feature branch: git checkout -b feature/lucia-auth-rbac"
echo ""
echo "2. **Fase de Implementación (CURRENT)**"
echo "   - Sistema RBAC granular: PermissionsService implementado ✓"
echo "   - PermissionGuard implementado ✓"
echo "   - Decoradores de conveniencia creados ✓"
echo ""
echo "3. **Fase de Testing**"
echo "   - Unit tests para PermissionsService"
echo "   - Integration tests para PermissionGuard"
echo "   - E2E tests para flujos de autorización"
echo "   - Testing con datos de staging"
echo ""
echo "4. **Fase de Deployment (canary)**"
echo "   - Deploy a staging first"
echo "   - Monitorear logs y errores"
echo "   - Validar login/logout/refresh"
echo "   - Validar permisos por endpoint"
echo ""
echo "5. **Fase de Rollback (si necesario)**"
echo "   - git revert cambios"
echo "   - Redeploy versión anterior"
echo "   - Limpiar sesiones DB si afectadas"
echo "   - Documentar lessons learned"
echo ""

echo "## Permisos Granulares Implementados"
echo ""
echo "### Productos"
echo "  - products:create - Crear productos"
echo "  - products:read - Ver productos"
echo "  - products:update - Actualizar productos"
echo "  - products:delete - Eliminar productos"
echo "  - products:view - Ver productos (solo lectura)"
echo ""
echo "### Recetas"
echo "  - recipes:create - Crear recetas"
echo "  - recipes:read - Ver recetas"
echo "  - recipes:update - Actualizar recetas"
echo "  - recipes:delete - Eliminar recetas"
echo "  - recipes:view - Ver recetas (solo lectura)"
echo ""
echo "### Menús"
echo "  - menus:create - Crear menús"
echo "  - menus:read - Ver menús"
echo "  - menus:update - Actualizar menús"
echo "  - menus:delete - Eliminar menús"
echo "  - menus:publish - Publicar menús"
echo "  - menus:view - Ver menús (solo lectura)"
echo ""
echo "### Almacenes"
echo "  - warehouses:create - Crear almacenes"
echo "  - warehouses:read - Ver almacenes"
echo "  - warehouses:update - Actualizar almacenes"
echo "  - warehouses:delete - Eliminar almacenes"
echo "  - warehouses:view - Ver almacenes (solo lectura)"
echo ""
echo "### Producción"
echo "  - production:create - Crear órdenes de producción"
echo "  - production:read - Ver producción"
echo "  - production:update - Actualizar producción"
echo "  - production:delete - Eliminar producción"
echo "  - production:view - Ver producción (solo lectura)"
echo "  - production:approve - Aprobar producción"
echo ""
echo "### Usuarios"
echo "  - users:create - Crear usuarios"
echo "  - users:read - Ver usuarios"
echo "  - users:update - Actualizar usuarios"
echo "  - users:delete - Eliminar usuarios"
echo "  - users:view - Ver usuarios (solo lectura)"
echo "  - users:manage_roles - Gestionar roles de usuarios"
echo ""
echo "### Dashboard"
echo "  - dashboard:view - Ver dashboard"
echo "  - dashboard:manage_alerts - Gestionar alertas"
echo "  - dashboard:export_reports - Exportar reportes"
echo ""
echo "### Configuración"
echo "  - settings:read - Ver configuración"
echo "  - settings:update - Actualizar configuración"
echo "  - settings:manage_categories - Gestionar categorías"
echo "  - settings:manage_suppliers - Gestionar proveedores"
echo ""

echo "## Roles y Permisos"
echo ""
echo "### ADMIN"
echo "  - Acceso completo a TODOS los permisos"
echo "  - Incluye gestión de usuarios y configuración"
echo ""
echo "### USER"
echo "  - Permisos limitados a operaciones operativas"
echo "  - No puede crear/eliminar usuarios"
echo "  - No puede modificar configuración global"
echo "  - Puede leer y actualizar la mayoría de recursos"
echo ""
echo "### VIEWER"
echo "  - Permisos de solo lectura"
echo "  - No puede modificar datos"
echo "  - Solo puede ver productos, recetas, menús, almacenes, producción, pedidos"
echo ""

echo "## Decoradores de Conveniencia"
echo ""
echo "Uso en controllers:"
echo "  @UseGuards(PermissionGuard, RequirePermissions('products:create', 'products:update'))"
echo "  @Post('products')"
echo "  async createProduct() { ... }"
echo ""
echo "O usar decoradores específicos:"
echo "  @UseGuards(PermissionGuard, CanCreateProducts())"
echo "  @Post('products')"
echo "  async createProduct() { ... }"
echo ""
echo "Decoradores disponibles:"
echo "  - RequirePermissions() - Permisos específicos (todos requeridos)"
echo "  - RequireAnyPermission() - Cualquiera de los permisos (al menos uno)"
echo "  - CanCreateProducts() - Crear productos"
echo "  - CanUpdateProducts() - Actualizar productos"
echo "  - CanDeleteProducts() - Eliminar productos"
echo "  - CanCreateRecipes() - Crear recetas"
echo "  - CanUpdateRecipes() - Actualizar recetas"
echo "  - CanDeleteRecipes() - Eliminar recetas"
echo "  - CanPublishMenus() - Publicar menús"
echo "  - CanDeleteMenus() - Eliminar menús"
echo "  - CanApproveProduction() - Aprobar producción"
echo "  - CanManageUsers() - Gestionar usuarios"
echo "  - CanManageSettings() - Gestionar configuración"
echo ""

echo "## Endpoint Mapping (Endpoints → Permisos)"
echo ""
echo "POST   /api/v1/products        → products:create"
echo "GET    /api/v1/products        → products:read"
echo "PUT    /api/v1/products/:id     → products:update"
echo "DELETE /api/v1/products/:id     → products:delete"
echo ""
echo "POST   /api/v1/recipes         → recipes:create"
echo "GET    /api/v1/recipes         → recipes:read"
echo "PUT    /api/v1/recipes/:id     → recipes:update"
echo "DELETE /api/v1/recipes/:id     → recipes:delete"
echo ""
echo "POST   /api/v1/menus            → menus:create"
echo "GET    /api/v1/menus            → menus:read"
echo "PUT    /api/v1/menus/:id         → menus:update"
echo "DELETE /api/v1/menus/:id         → menus:delete"
echo "POST   /api/v1/menus/:id/publish → menus:publish"
echo ""
echo "POST   /api/v1/production/orders → production:create"
echo "POST   /api/v1/production/orders/:id/approve → production:approve"
echo ""
echo "POST   /api/v1/users            → users:create"
echo "PUT    /api/v1/users/:id/roles  → users:manage_roles"
echo ""

echo "## Procedimiento de Rollback"
echo ""
echo "1. **Rollback de Código**"
echo "   git checkout develop"
echo "   git branch -D feature/lucia-auth-rbac"
echo ""
echo "2. **Rollback de Deploy**"
echo "   Dokploy: Redeploy desde develop"
echo "   GitHub: Revert merge si fue merged"
echo ""
echo "3. **Rollback de Datos** (solo si se migraron datos)"
echo "   Restaurar backup de DB antes de migración"
echo "   Validar integridad de datos"
echo ""
echo "4. **Post-Mortem**"
echo "   Analizar logs de errores"
echo "   Documentar lessons learned"
echo "   Planificar mejoras para próximo intento"
echo ""

echo "## Monitoreo Post-Migración"
echo ""
echo "KPIs a monitorear:"
echo "  - Login success rate"
echo "  - Logout success rate"
echo "  - Session refresh rate"
echo "  - Permission denied errors (403)"
echo "  - Session validation errors (401)"
echo "  - Concurrent sessions per user"
echo "  - Session expiry rate"
echo ""
echo "Alertas críticas:"
echo "  - Spike en 403 Forbidden errors"
echo "  - Spike en 401 Unauthorized errors"
echo "  - Login failures > 5% threshold"
echo "  - Session refresh failures"
echo "  - Concurrent sessions > 10 por usuario"
echo ""

echo "=== Fin de Documentación de Migración ==="
echo ""
echo "Estado: Implementación COMPLETA"
echo "Próximos pasos: Testing → Deployment Canary → Production"