import { CreateSictedPracticeDto } from "../dto/sicted-practice-catalog.dto";

/**
 * Catálogo real de 144 buenas prácticas del manual "Restaurantes y empresas
 * turísticas de catering: Manual de buenas prácticas" (v4, Compromiso de Calidad
 * Turística / SICTED) — extraído con `pdftotext -layout` del PDF real
 * (`23_Restaurantes_y_empresas_de_catering_v4.pdf`, 58 págs., carpeta
 * `artefactos/SICTED/Manuales/`), NO inventado. Corrige un hallazgo de esta misma
 * fase: la escala real es "Puntuación: 1 a 5" + casilla "No aplica" separada por
 * práctica (no "1,3,4,5,6=NA" como asumía el diseño original de fase 9), y la
 * estructura real es BP1-BP6 (no códigos LEG/DIR/PER/PROV).
 *
 * BP1-BP5 son secciones genéricas (73 prácticas); BP6 Oficio trae 71 prácticas
 * aplicables a "Restaurantes" — se excluyeron 16 prácticas de BP6 marcadas
 * exclusivamente "(C)" en el manual (solo para empresas de catering; Warynessy es
 * restaurante, no catering). `isMandatory` viene del listado real "Buenas
 * prácticas obligatorias de la sección BPx" de cada sección, no es una suposición
 * — el manual advierte: la puntuación mínima de cada obligatoria ha de ser 3 o
 * superior para optar al distintivo.
 */
export const SICTED_PRACTICE_CATALOG_SEED: CreateSictedPracticeDto[] = [
  {
    code: "1.1",
    bpSection: 1,
    bpSectionName: "Personas",
    title: "Se conoce y se cumple con la normativa legal vigente que aplica",
    isMandatory: true,
  },
  {
    code: "1.2",
    bpSection: 1,
    bpSectionName: "Personas",
    title:
      "Existe un organigrama y están definidas las responsabilidades por puesto de trabajo",
    isMandatory: true,
  },
  {
    code: "1.3",
    bpSection: 1,
    bpSectionName: "Personas",
    title: "Se utiliza la planificación como herramienta de organización",
    isMandatory: true,
  },
  {
    code: "1.4",
    bpSection: 1,
    bpSectionName: "Personas",
    title: "Están definidos los periodos de estacionalidad",
    isMandatory: false,
  },
  {
    code: "1.5",
    bpSection: 1,
    bpSectionName: "Personas",
    title:
      "Está definida la plantilla mínima para cubrir las necesidades de servicio al cliente",
    isMandatory: true,
  },
  {
    code: "1.6",
    bpSection: 1,
    bpSectionName: "Personas",
    title:
      "Existe un interlocutor continuo entre la empresa/servicio turístico y el Gestor SICTED del destino",
    isMandatory: true,
  },
  {
    code: "1.7",
    bpSection: 1,
    bpSectionName: "Personas",
    title:
      "El equipo se reúne periódicamente para solucionar aspectos críticos",
    isMandatory: true,
  },
  {
    code: "1.8",
    bpSection: 1,
    bpSectionName: "Personas",
    title:
      "Se informa al trabajador de reciente incorporación de sus funciones y responsabilidades.",
    isMandatory: true,
  },
  {
    code: "1.9",
    bpSection: 1,
    bpSectionName: "Personas",
    title: "Existe un Plan de formación para el personal",
    isMandatory: true,
  },
  {
    code: "1.10",
    bpSection: 1,
    bpSectionName: "Personas",
    title: "Existen directrices sobre vestuario y el aspecto personal",
    isMandatory: true,
  },
  {
    code: "1.11",
    bpSection: 1,
    bpSectionName: "Personas",
    title: "El personal que mantiene relación con el cliente está identificado",
    isMandatory: false,
  },
  {
    code: "1.12",
    bpSection: 1,
    bpSectionName: "Personas",
    title: "El personal aplica fórmulas de cortesía y trato al cliente",
    isMandatory: true,
  },
  {
    code: "1.13",
    bpSection: 1,
    bpSectionName: "Personas",
    title: "El personal tiene conocimiento básico de idiomas",
    isMandatory: true,
  },
  {
    code: "1.14",
    bpSection: 1,
    bpSectionName: "Personas",
    title: "Se promueve la comunicación interna",
    isMandatory: true,
  },
  {
    code: "1.15",
    bpSection: 1,
    bpSectionName: "Personas",
    title: "Se dispone de un grado mínimo de informatización",
    isMandatory: false,
  },
  {
    code: "1.16",
    bpSection: 1,
    bpSectionName: "Personas",
    title:
      "El equipo conoce y aplica el Plan de prevención de riesgos laborales y el Plan de emergencia y evacuación",
    isMandatory: true,
  },
  {
    code: "1.17",
    bpSection: 1,
    bpSectionName: "Personas",
    title: "El personal conoce cómo actuar en caso de accidente",
    isMandatory: true,
  },
  {
    code: "1.18",
    bpSection: 1,
    bpSectionName: "Personas",
    title:
      "Existe un trabajador con formación en seguridad y primeros auxilios",
    isMandatory: false,
  },
  {
    code: "1.19",
    bpSection: 1,
    bpSectionName: "Personas",
    title: "Se emplean criterios de gestión medioambiental",
    isMandatory: false,
  },
  {
    code: "1.20",
    bpSection: 1,
    bpSectionName: "Personas",
    title: "Se realiza una autoevaluación del Manual de buenas prácticas",
    isMandatory: true,
  },
  {
    code: "1.21",
    bpSection: 1,
    bpSectionName: "Personas",
    title:
      "Se revisa el cumplimiento de los criterios de gestión de la calidad",
    isMandatory: true,
  },
  {
    code: "2.1",
    bpSection: 2,
    bpSectionName: "Clientes",
    title: "El personal asume un rol dinámico frente al cliente",
    isMandatory: true,
  },
  {
    code: "2.2",
    bpSection: 2,
    bpSectionName: "Clientes",
    title: "Existen directrices para el tratamiento de quejas y reclamaciones",
    isMandatory: true,
  },
  {
    code: "2.3",
    bpSection: 2,
    bpSectionName: "Clientes",
    title:
      "Se dispone de un soporte que invita al cliente a registrar una queja y/o sugerencia",
    isMandatory: true,
  },
  {
    code: "2.4",
    bpSection: 2,
    bpSectionName: "Clientes",
    title:
      "Se lleva un seguimiento de la solución adoptada ante una queja y/o sugerencia",
    isMandatory: true,
  },
  {
    code: "2.5",
    bpSection: 2,
    bpSectionName: "Clientes",
    title:
      "La empresa/servicio turístico dispone de un cuestionario de satisfacción del cliente",
    isMandatory: true,
  },
  {
    code: "2.6",
    bpSection: 2,
    bpSectionName: "Clientes",
    title: "La opinión del cliente se utiliza para mejorar el servicio",
    isMandatory: true,
  },
  {
    code: "2.7",
    bpSection: 2,
    bpSectionName: "Clientes",
    title:
      "Se comunica a todo el equipo los resultados obtenidos de la encuesta",
    isMandatory: false,
  },
  {
    code: "2.8",
    bpSection: 2,
    bpSectionName: "Clientes",
    title:
      "El personal conoce el espacio turístico próximo al establecimiento y es capaz de ofrecer",
    isMandatory: true,
  },
  {
    code: "2.9",
    bpSection: 2,
    bpSectionName: "Clientes",
    title: "El personal cuida su imagen frente al cliente",
    isMandatory: true,
  },
  {
    code: "2.10",
    bpSection: 2,
    bpSectionName: "Clientes",
    title: "Se informa al cliente de las prácticas ambientales",
    isMandatory: false,
  },
  {
    code: "2.11",
    bpSection: 2,
    bpSectionName: "Clientes",
    title: "Existe una política de objetos perdidos",
    isMandatory: true,
  },
  {
    code: "3.1",
    bpSection: 3,
    bpSectionName: "Ventas",
    title:
      "Todo el equipo de trabajo conoce el producto/servicio que ofrece/vende",
    isMandatory: true,
  },
  {
    code: "3.2",
    bpSection: 3,
    bpSectionName: "Ventas",
    title: "Los precios de los productos/servicios están expuestos",
    isMandatory: true,
  },
  {
    code: "3.3",
    bpSection: 3,
    bpSectionName: "Ventas",
    title: "Se exhiben los medios de pago que son aceptados",
    isMandatory: true,
  },
  {
    code: "3.4",
    bpSection: 3,
    bpSectionName: "Ventas",
    title: "Se emite ticket o factura",
    isMandatory: true,
  },
  {
    code: "3.5",
    bpSection: 3,
    bpSectionName: "Ventas",
    title: "La información que se proporciona al cliente es objetiva",
    isMandatory: true,
  },
  {
    code: "3.6",
    bpSection: 3,
    bpSectionName: "Ventas",
    title: "Los soportes tienen un diseño atractivo",
    isMandatory: true,
  },
  {
    code: "3.7",
    bpSection: 3,
    bpSectionName: "Ventas",
    title: "Se participa en las acciones de promoción del destino",
    isMandatory: false,
  },
  {
    code: "3.8",
    bpSection: 3,
    bpSectionName: "Ventas",
    title:
      "Se facilita información de la empresa/servicio turístico al destino",
    isMandatory: false,
  },
  {
    code: "3.9",
    bpSection: 3,
    bpSectionName: "Ventas",
    title: "Existe información comercial en varios idiomas",
    isMandatory: false,
  },
  {
    code: "3.10",
    bpSection: 3,
    bpSectionName: "Ventas",
    title:
      "Se dispone de web para dar a conocer y/o comercializar el producto/servicio",
    isMandatory: false,
  },
  {
    code: "4.1",
    bpSection: 4,
    bpSectionName: "Servicios externos",
    title: "Existe una base de datos de proveedores",
    isMandatory: true,
  },
  {
    code: "4.2",
    bpSection: 4,
    bpSectionName: "Servicios externos",
    title: "Existe una selección de proveedores con los que trabajar",
    isMandatory: false,
  },
  {
    code: "4.3",
    bpSection: 4,
    bpSectionName: "Servicios externos",
    title: "Se formalizan las compras",
    isMandatory: true,
  },
  {
    code: "4.4",
    bpSection: 4,
    bpSectionName: "Servicios externos",
    title: "Periódicamente se evalúa a los proveedores principales",
    isMandatory: false,
  },
  {
    code: "4.5",
    bpSection: 4,
    bpSectionName: "Servicios externos",
    title: "Se utilizan criterios medioambientales en las decisiones de compra",
    isMandatory: true,
  },
  {
    code: "4.6",
    bpSection: 4,
    bpSectionName: "Servicios externos",
    title: "Está establecido el horario de recepción de mercancías",
    isMandatory: false,
  },
  {
    code: "4.7",
    bpSection: 4,
    bpSectionName: "Servicios externos",
    title: "Existen directrices para la recepción de pedidos",
    isMandatory: true,
  },
  {
    code: "4.8",
    bpSection: 4,
    bpSectionName: "Servicios externos",
    title: "Están definidos los stocks mínimos",
    isMandatory: true,
  },
  {
    code: "4.9",
    bpSection: 4,
    bpSectionName: "Servicios externos",
    title: "Periódicamente se realizan inventarios",
    isMandatory: true,
  },
  {
    code: "4.10",
    bpSection: 4,
    bpSectionName: "Servicios externos",
    title:
      "Se asegura la rotación de los productos en el sistema de almacenamiento",
    isMandatory: true,
  },
  {
    code: "4.11",
    bpSection: 4,
    bpSectionName: "Servicios externos",
    title: "Se registran las incidencias con proveedores",
    isMandatory: true,
  },
  {
    code: "5.1",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "La empresa/servicio turístico dispone de señalización posicional",
    isMandatory: true,
  },
  {
    code: "5.2",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Existe señalización direccional interna",
    isMandatory: true,
  },
  {
    code: "5.3",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Se dispone de los elementos de seguridad necesarios",
    isMandatory: true,
  },
  {
    code: "5.4",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "La zona de uso del cliente es un espacio agradable y atractivo",
    isMandatory: true,
  },
  {
    code: "5.5",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title:
      "Se dispone de adecuados sistemas de calefacción y refrigeración en el área de servicio al cliente",
    isMandatory: true,
  },
  {
    code: "5.6",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title:
      "El equipamiento es acorde con el servicio que se presta y está en perfecto estado",
    isMandatory: true,
  },
  {
    code: "5.7",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Existe un equipamiento completo en los aseos públicos",
    isMandatory: true,
  },
  {
    code: "5.8",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Se realiza una limpieza sistemática de los aseos públicos",
    isMandatory: true,
  },
  {
    code: "5.9",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Las zonas exteriores se limpian periódicamente",
    isMandatory: true,
  },
  {
    code: "5.10",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Existe un Plan de limpieza de las instalaciones y/o equipamiento",
    isMandatory: true,
  },
  {
    code: "5.11",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Se limpia en momentos de menor presencia de clientes",
    isMandatory: true,
  },
  {
    code: "5.12",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Los productos de limpieza están convenientemente envasados",
    isMandatory: true,
  },
  {
    code: "5.13",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Se dispone de un lugar donde guardar el equipamiento de limpieza",
    isMandatory: true,
  },
  {
    code: "5.14",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Existe un Plan de mantenimiento preventivo",
    isMandatory: true,
  },
  {
    code: "5.15",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Se realizan las revisiones que la normativa aplicable exige",
    isMandatory: true,
  },
  {
    code: "5.16",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title:
      "Se efectuan las labores de desinfección, desinsectación y desratización fijadas por normativa",
    isMandatory: true,
  },
  {
    code: "5.17",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Se dispone y se hace uso del parte de averías o similar",
    isMandatory: true,
  },
  {
    code: "5.18",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title:
      "Se cumple lo exigido en materia de accesibilidad para personas con movilidad reducida",
    isMandatory: true,
  },
  {
    code: "5.19",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Se dispone de un botiquín de primeros auxilios",
    isMandatory: true,
  },
  {
    code: "5.20",
    bpSection: 5,
    bpSectionName: "Instalaciones y equipamiento",
    title: "Se realiza una correcta clasificación de residuos",
    isMandatory: true,
  },
  {
    code: "6.1",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Está expuesto el aforo del establecimiento",
    isMandatory: true,
  },
  {
    code: "6.2",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "La carta está expuesta en el exterior",
    isMandatory: true,
  },
  {
    code: "6.3",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Los horarios están expuestos",
    isMandatory: true,
  },
  {
    code: "6.4",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se asegura un espacio mínimo entre las mesas",
    isMandatory: true,
  },
  {
    code: "6.5",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title:
      "Se dispone de un mobiliario en sala confortable, acogedor y en perfecto estado de conservación",
    isMandatory: true,
  },
  {
    code: "6.6",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "La vajilla se encuentra siempre en óptimas condiciones",
    isMandatory: true,
  },
  {
    code: "6.7",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se emplea vajilla típica para el servicio de ciertos platos",
    isMandatory: false,
  },
  {
    code: "6.8",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "La cristalería está siempre limpia y en buen estado",
    isMandatory: true,
  },
  {
    code: "6.9",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "La lencería de mesa está limpia y en buenas condiciones",
    isMandatory: true,
  },
  {
    code: "6.10",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title:
      "La cubertería y los elementos auxiliares presentan un buen estado de conservación y limpieza.",
    isMandatory: true,
  },
  {
    code: "6.11",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title:
      "Se dispone de suficiente equipamiento para la prestación del servicio",
    isMandatory: true,
  },
  {
    code: "6.12",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se dispone de cartas y soportes de venta en cantidad suficiente",
    isMandatory: true,
  },
  {
    code: "6.13",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se dispone de una carta con menús especiales",
    isMandatory: false,
  },
  {
    code: "6.14",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "El mobiliario de servicio tiene una ubicación adecuada",
    isMandatory: false,
  },
  {
    code: "6.15",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Existen tronas o sillas específicas para niños",
    isMandatory: true,
  },
  {
    code: "6.16",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se dispone de medios de cobro suficientes",
    isMandatory: true,
  },
  {
    code: "6.17",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Los medios de pago están expuestos",
    isMandatory: true,
  },
  {
    code: "6.18",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title:
      "No existen elementos que puedan distorsionar el ambiente del establecimiento",
    isMandatory: true,
  },
  {
    code: "6.19",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se acompaña al cliente a la mesa",
    isMandatory: false,
  },
  {
    code: "6.20",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se entregan inmediatamente las cartas",
    isMandatory: true,
  },
  {
    code: "6.21",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Existe un responsable que asesora en la selección de vinos",
    isMandatory: false,
  },
  {
    code: "6.22",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se prioriza la toma de la comanda",
    isMandatory: true,
  },
  {
    code: "6.23",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se asegura que la duración de las esperas es la adecuada",
    isMandatory: true,
  },
  {
    code: "6.24",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "El remonte de las mesas se realiza de una manera ágil",
    isMandatory: true,
  },
  {
    code: "6.25",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se incluyen productos y/o preparaciones autóctonas de la zona",
    isMandatory: false,
  },
  {
    code: "6.26",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title:
      "Se asegura que el cliente dispone de todos los complementos necesarios",
    isMandatory: true,
  },
  {
    code: "6.27",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se presta una continua atención al cliente",
    isMandatory: true,
  },
  {
    code: "6.28",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se garantiza la prestación sin prisas del servicio",
    isMandatory: true,
  },
  {
    code: "6.29",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "La factura se entrega cuando el cliente lo solicita",
    isMandatory: true,
  },
  {
    code: "6.30",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "La presentación de la factura es cuidadosa",
    isMandatory: true,
  },
  {
    code: "6.31",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Las facturas tienen un formato estándar",
    isMandatory: true,
  },
  {
    code: "6.32",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se garantiza la correcta puesta a punto de la sala",
    isMandatory: true,
  },
  {
    code: "6.33",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se asegura un servicio inmediato",
    isMandatory: true,
  },
  {
    code: "6.34",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "El tiempo se gestiona de la forma más eficaz posible",
    isMandatory: true,
  },
  {
    code: "6.35",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title:
      "Existe una forma de trabajar estandarizada atendiendo a ciertas pautas de comportamiento",
    isMandatory: true,
  },
  {
    code: "6.36",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se procura el fácil acceso a los elementos auxiliares para el café",
    isMandatory: false,
  },
  {
    code: "6.37",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se emplean vitrinas refrigeradas",
    isMandatory: true,
  },
  {
    code: "6.38",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se controla la temperatura de la zona de manipulación en frío",
    isMandatory: true,
  },
  {
    code: "6.39",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se dispone de equipamiento acorde a las necesidades del servicio",
    isMandatory: true,
  },
  {
    code: "6.40",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Existe una zona de almacenaje de bebidas",
    isMandatory: true,
  },
  {
    code: "6.41",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se agiliza el proceso de limpieza y acondicionamiento de la barra",
    isMandatory: true,
  },
  {
    code: "6.42",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title:
      "Se presta especial atención a la uniformidad e higiene del personal de cocina",
    isMandatory: true,
  },
  {
    code: "6.43",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title:
      "Se cumple la normativa legal relativa a seguridad e higiene alimentaria",
    isMandatory: true,
  },
  {
    code: "6.44",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title:
      "Existen hábitos de trabajo conocidos y aplicados por el personal de cocina",
    isMandatory: true,
  },
  {
    code: "6.45",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Los platos y productos son atractivos a la vista",
    isMandatory: true,
  },
  {
    code: "6.46",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se evita hacer excesivo ruido",
    isMandatory: true,
  },
  {
    code: "6.47",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se controla la temperatura de las cámaras de cocina y restaurante",
    isMandatory: true,
  },
  {
    code: "6.48",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Los alimentos se conservan garantizando su estado óptimo",
    isMandatory: true,
  },
  {
    code: "6.49",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Existe una correcta ventilación en las instalaciones de cocina",
    isMandatory: true,
  },
  {
    code: "6.50",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "El tratamiento de productos refrigerados o congelados es correcto",
    isMandatory: true,
  },
  {
    code: "6.51",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "La manipulación de alimentos es la correcta",
    isMandatory: true,
  },
  {
    code: "6.52",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title:
      "Se realiza un escandallo para cada uno de los principales platos de la carta",
    isMandatory: false,
  },
  {
    code: "6.53",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title:
      "Existe una receta para cada uno de los principales platos de la carta",
    isMandatory: true,
  },
  {
    code: "6.54",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se identifican y seleccionan indicadores de ventas",
    isMandatory: false,
  },
  {
    code: "6.55",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title:
      "Existe un Plan de limpieza específico para las instalaciones y equipamiento de cocina y economato",
    isMandatory: true,
  },
  {
    code: "6.56",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "La cocina se limpia correctamente",
    isMandatory: true,
  },
  {
    code: "6.57",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se dispone de equipamiento acorde a las necesidades de cocina",
    isMandatory: true,
  },
  {
    code: "6.58",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Las instalaciones de cocina se ciñen a la normativa legal vigente",
    isMandatory: true,
  },
  {
    code: "6.59",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se organiza adecuadamente el área de fregadero",
    isMandatory: true,
  },
  {
    code: "6.60",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "El tratamiento de desperdicios se realiza correctamente",
    isMandatory: true,
  },
  {
    code: "6.61",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se emplea material de embalaje apropiado al producto vendido",
    isMandatory: true,
  },
  {
    code: "6.62",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title:
      "En el material de embalaje existe un indicativo del establecimiento",
    isMandatory: true,
  },
  {
    code: "6.63",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Los productos y artículos tienen el precio visible",
    isMandatory: true,
  },
  {
    code: "6.64",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "La música ambiental es agradable",
    isMandatory: true,
  },
  {
    code: "6.65",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Existen papeleras a disposición del cliente",
    isMandatory: true,
  },
  {
    code: "6.66",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se dispone de mobiliario acorde a las características del comercio",
    isMandatory: true,
  },
  {
    code: "6.67",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "El escaparate se encuentra ordenado y limpio",
    isMandatory: true,
  },
  {
    code: "6.68",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Se cuida el orden y colocación de los productos",
    isMandatory: true,
  },
  {
    code: "6.69",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Los embalajes de los productos no se encuentran visibles",
    isMandatory: true,
  },
  {
    code: "6.70",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "Existe una separación clara y coherente entre distintos productos",
    isMandatory: true,
  },
  {
    code: "6.71",
    bpSection: 6,
    bpSectionName: "Oficio (Restaurantes)",
    title: "La información promocional es clara y visible",
    isMandatory: true,
  },
];
